version: "3.8"
services:
  redis-server:
    image: "redis/redis-stack-server:latest"
    volumes:
      - ./configurations/redis/data:/data
      - ./configurations/redis/conf:/conf
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server
    command: /conf/redis.conf
    deploy:
      restart_policy:
        condition: on-failure
  node-server:
    image: "sage3/next:prod"
    ports:
      - "443:443"
    depends_on:
      - "redis-server"
    volumes:
      - ./configurations/node/keys:/app/keys
      - ./configurations/node/assets:/app/dist/apps/homebase/assets
      - ./configurations/node/sage3-prod.hjson:/app/sage3-prod.hjson
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s
  python:
    image: "python:3.9-bullseye"
    volumes:
      - ./configurations/python:/code
    environment:
      - ENVIRONMENT=production
      - SAGE3_SERVER=${HOST}
    command: sleep infinity
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s
  jupyter:
    image: "jupyter/datascience-notebook"
    volumes:
      - ./configurations/jupyter/conf:/conf
      - ./configurations/jupyter/notebooks:/home/jovyan/notebooks
      - ./redis-client:/home/jovyan/work
    ports:
      - "4443:8888"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - "redis-server"
    command: /conf/start.sh
    deploy:
      restart_policy:
        condition: on-failure
