version: "3.8"
services:
  redis-server:
    image: "redis/redis-stack-server:latest"
    volumes:
      - ./configurations/redis/data:/data
      - ./configurations/redis/conf:/conf
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server
    command: /conf/redis.conf
    deploy:
      restart_policy:
        condition: on-failure
  node-server:
    image: "sage3/next:arm64"
    ports:
      - "443:443"
    depends_on:
      - "redis-server"
    volumes:
      - ./configurations/node/keys:/app/keys
      - ./configurations/node/assets:/app/dist/apps/homebase/assets
      - ./configurations/node/sage3-prod.hjson:/app/sage3-prod.hjson
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "https://${HOST}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
  python:
    image: "sage3/foresight:arm64"
    environment:
      - ENVIRONMENT=production
      - SAGE3_SERVER=${HOST}
      - ROOM_ID=521f75cc-0a02-4ae2-8f3f-0b190bc2b1a0
    restart: always
    working_dir: /app
    command: python proxy.py
    depends_on:
      node-server:
        condition: service_healthy
  jupyter:
    image: "jupyter/datascience-notebook"
    volumes:
      - ./configurations/jupyter/conf:/conf
      - ./configurations/jupyter/notebooks:/home/jovyan/notebooks
      - ./redis-client:/home/jovyan/work
    ports:
      - "4443:8888"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - "redis-server"
    command: /conf/start.sh
    deploy:
      restart_policy:
        condition: on-failure
